### ISSUE TITLE
Dgraph constructor key

### ISSUE THREAD

**Issue by elonezra** [dean985/mazewaze#11]
צריך לבדוק מצב שאם מחקתי צומת אז אפשר למחזר את המפתח שלו

**Comment by dean985** [comment]
למה לשחזר?
אם מחקת צומת ואתה רוצה לשחזר אותה, היא צריכה מקום בזכרון ...
האם צריך לזכור את כל הצמתים שנמחקו? או רק צומת אחרון שנמחק?
