### ISSUE TITLE
execute Data structuer

### ISSUE THREAD

**Issue by elonezra** [dean985/mazewaze#3]
- [x]  edge_data.java - @dean985 

- [ ] node_data.java - @elonezra 

- [ ] graph.java - 

DGraph is implementing the interface graph ( a directed weighted graph)
Weighted Graph - 
https://he.wikipedia.org/wiki/%D7%92%D7%A8%D7%A3_%D7%9E%D7%9E%D7%95%D7%A9%D7%A7%D7%9C

**Comment by dean985** [comment]
First draft of Edge is done.
